'use client'

import { useState, useEffect } from 'react'
import { Event } from '../../lib/types/entity'
import { EventFormData } from '../../lib/validation'
import { ProgressCircle } from '../Event/ProgressCircle'
import { CreateEventDialog } from '../Event/CreateEventDialog'
import { EditEventDialog } from '../Event/EditEventDialog'
import { Button } from '../ui/button'
import { Input } from '../ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../ui/table'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '../ui/card'
import { Checkbox } from '../ui/checkbox'

export default function EventList() {
  const [events, setEvents] = useState<Event[]>([])
  const [searchTerm, setSearchTerm] = useState('')
  const [sortBy, setSortBy] = useState<'priority' | 'startTime' | 'endTime'>('priority')
  const [filterComplete, setFilterComplete] = useState<'all' | 'complete' | 'incomplete'>('all')

  useEffect(() => {
    // In a real application, you would fetch events from an API here
    // For this example, we'll use some dummy data
    const dummyEvents: Event[] = [
      {
        eventId: '1',
        summary: 'Team Meeting',
        description: 'Weekly team sync',
        startTime: '2023-06-01T10:00:00Z',
        endTime: '2023-06-01T11:00:00Z',
        isRecurring: true,
        isComplete: false,
        type: 'task',
        priority: 3
      },
      {
        eventId: '2',
        summary: 'Project Deadline',
        description: 'Submit final project report',
        startTime: '2023-06-15T17:00:00Z',
        endTime: '2023-06-15T18:00:00Z',
        isRecurring: false,
        isComplete: false,
        type: 'task',
        priority: 5
      }
    ]
    setEvents(dummyEvents)
  }, [])

  const handleCreateEvent = (data: EventFormData) => {
    const newEvent: Event = {
      ...data,
      eventId: Date.now().toString() // In a real app, this would be generated by the backend
    }
    setEvents([...events, newEvent])
  }

  const handleEditEvent = (data: EventFormData) => {
    const updatedEvents = events.map((event) => (event.eventId === data.eventId ? { ...event, ...data } : event))
    setEvents(updatedEvents)
  }

  const handleDeleteEvent = (eventId: string) => {
    setEvents(events.filter((event) => event.eventId !== eventId))
  }

  const handleFastChangeComplete = (eventId: string) => {
    setEvents(events.map((event) => (event.eventId === eventId ? { ...event, isComplete: !event.isComplete } : event)))
  }

  const handleFastChangePriority = (eventId: string, newPriority: number) => {
    setEvents(events.map((event) => (event.eventId === eventId ? { ...event, priority: newPriority } : event)))
  }

  const filteredAndSortedEvents = events
    .filter(
      (event) =>
        event.summary.toLowerCase().includes(searchTerm.toLowerCase()) ||
        event.description.toLowerCase().includes(searchTerm.toLowerCase())
    )
    .filter((event) => {
      if (filterComplete === 'complete') return event.isComplete
      if (filterComplete === 'incomplete') return !event.isComplete
      return true
    })
    .sort((a, b) => {
      if (sortBy === 'priority') return b.priority - a.priority
      if (sortBy === 'startTime') return new Date(a.startTime).getTime() - new Date(b.startTime).getTime()
      if (sortBy === 'endTime') return new Date(a.endTime).getTime() - new Date(b.endTime).getTime()
      return 0
    })

  const completedEventsCount = events.filter((event) => event.isComplete).length
  const totalProgress = Math.round((completedEventsCount / events.length) * 100) || 0

  return (
    <div className='container mx-auto p-4'>
      <div className='flex justify-between w-full items-center mb-8'>
        <div className='flex flex-col justify-start items-start space-y-4'>
          <Card className='w-full'>
            <CardHeader>
              <CardTitle>Total Events</CardTitle>
            </CardHeader>
            <CardContent>{events.length}</CardContent>
            <CardFooter>
              <CardDescription>
                Complete: {events.filter((event) => event.isComplete).length}, In Progress:{' '}
                {events.filter((event) => !event.isComplete).length}
              </CardDescription>
            </CardFooter>
          </Card>
        </div>
        <div>
          <h2 className='text-2xl font-bold mb-2'>Overall Progress</h2>
          <ProgressCircle progress={totalProgress} size={200} strokeWidth={20} />
        </div>

        <div>
          <CreateEventDialog onCreateEvent={handleCreateEvent} />
        </div>
      </div>

      <div className='mb-8'>
        <h2 className='text-xl font-semibold mb-2'>Manage Events</h2>
        <div className='flex space-x-4 mb-4 w-full'>
          <Input
            placeholder='Search events...'
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className='flex-1'
          />
          <Select value={sortBy} onValueChange={(value: 'priority' | 'startTime' | 'endTime') => setSortBy(value)}>
            <SelectTrigger className='w-[180px]'>
              <SelectValue placeholder='Sort by' />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value='priority'>Priority</SelectItem>
              <SelectItem value='startTime'>Start Time</SelectItem>
              <SelectItem value='endTime'>End Time</SelectItem>
            </SelectContent>
          </Select>
          <Select
            value={filterComplete}
            onValueChange={(value: 'all' | 'complete' | 'incomplete') => setFilterComplete(value)}
          >
            <SelectTrigger className='w-[180px]'>
              <SelectValue placeholder='Filter by status' />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value='all'>All</SelectItem>
              <SelectItem value='complete'>Complete</SelectItem>
              <SelectItem value='incomplete'>Incomplete</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Summary</TableHead>
              <TableHead>Start Time</TableHead>
              <TableHead>End Time</TableHead>
              <TableHead>Priority</TableHead>
              <TableHead>Complete</TableHead>
              <TableHead>Actions</TableHead>
              <TableHead>Priority </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredAndSortedEvents.map((event) => (
              <TableRow key={event.eventId}>
                <TableCell>{event.summary}</TableCell>
                <TableCell>{new Date(event.startTime).toLocaleString()}</TableCell>
                <TableCell>{new Date(event.endTime).toLocaleString()}</TableCell>
                <TableCell>{event.priority}</TableCell>
                <TableCell>
                  <Checkbox
                    checked={event.isComplete}
                    onCheckedChange={() => handleFastChangeComplete(event.eventId)}
                  />
                </TableCell>
                <TableCell>
                  <div className='flex space-x-2'>
                    <EditEventDialog event={event} onEditEvent={handleEditEvent} />
                    <Button onClick={() => handleDeleteEvent(event.eventId)} variant='destructive'>
                      Delete
                    </Button>
                  </div>
                </TableCell>
                <TableCell>
                  <Select
                    value={event.priority.toString()}
                    onValueChange={(value) => handleFastChangePriority(event.eventId, parseInt(value))}
                  >
                    <SelectTrigger className='w-[100px]'>
                      <SelectValue placeholder='Priority' />
                    </SelectTrigger>
                    <SelectContent>
                      {[1, 2, 3, 4, 5].map((priority) => (
                        <SelectItem key={priority} value={priority.toString()}>
                          {priority}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
